---
- name: Install and configure Grafana with Prometheus datasource
  hosts: monitor-server
  become: true
  vars:
    node_exporter_host: "{{ groups['monitor-server'][0] }}"

  tasks:
    - name: Add Grafana repository key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana APT repository
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present

    - name: Install Grafana
      apt:
        name: grafana
        state: present

    - name: Start and enable Grafana service
      service:
        name: grafana-server
        state: started
        enabled: yes
